### ISSUE TITLE
Refactor: 리뷰 요청사항 반영

### ISSUE THREAD

**Issue by jsh00325** [kakao-tech-campus-2nd-step3/Team23_Android#59]
### ✨ 구현 기능 리스트
- [x] 백그라운드 작업이 아닌 경우의 코루틴 수정 (#18)
- [x] 영수증 수기 입력에서 (-) 버튼 문제 수정 (#23)
- [x] Ocr, User 모듈의 DI 모듈 위치 수정 (#46)
- [x] 모임 생성 페이지에서 Two-way 바인딩 적용 (#52)
- [x] domain:user 모듈의 이름 변경 (#56)

### 🔍 구현 목적(사용 이유)
- 기존 PR에서 받은 피드백을 적용하기 위해서
